"""Deterministic HTML and plain-text executive report formatting."""

from __future__ import annotations

import html
from datetime import datetime, timezone

from ..ai.models import ExecutiveAnalysis
from .models import NotificationRequest

REPORT_TITLE = "DriftMind Infrastructure Intelligence Report"


class ReportFormattingError(ValueError):
    """Raised when an executive analysis cannot be formatted safely."""


def _format_timestamp(generated_at: datetime) -> str:
    if not isinstance(generated_at, datetime):
        raise ReportFormattingError("generated_at must be a datetime")
    if generated_at.tzinfo is None or generated_at.utcoffset() is None:
        raise ReportFormattingError("generated_at must be timezone-aware")
    return (
        generated_at.astimezone(timezone.utc)
        .isoformat(timespec="seconds")
        .replace("+00:00", "Z")
    )


def _escape(value: str) -> str:
    normalized = value.replace("\r\n", "\n").replace("\r", "\n")
    return html.escape(normalized, quote=True).replace("\n", "<br>")


def format_html_report(
    analysis: ExecutiveAnalysis,
    generated_at: datetime,
) -> str:
    """Render an escaped, SES-compatible HTML report."""
    if not isinstance(analysis, ExecutiveAnalysis):
        raise ReportFormattingError("analysis must be an ExecutiveAnalysis")
    analysis.validate()
    timestamp = _format_timestamp(generated_at)
    if analysis.recommendations:
        recommendation_html = "\n".join(
            f"      <li>{_escape(recommendation.text)}</li>"
            for recommendation in analysis.recommendations
        )
        recommendations = f"    <ul>\n{recommendation_html}\n    </ul>"
    else:
        recommendations = "    <p>No recommendations provided.</p>"

    return "\n".join(
        (
            "<!DOCTYPE html>",
            '<html lang="en">',
            "<head>",
            '  <meta charset="utf-8">',
            f"  <title>{REPORT_TITLE}</title>",
            "</head>",
            "<body>",
            f"  <h1>{REPORT_TITLE}</h1>",
            f"  <p><strong>Generated:</strong> {timestamp}</p>",
            "  <section>",
            "    <h2>Executive Summary</h2>",
            f"    <p>{_escape(analysis.summary)}</p>",
            "  </section>",
            "  <section>",
            "    <h2>Security Impact</h2>",
            f"    <p>{_escape(analysis.security_impact)}</p>",
            "  </section>",
            "  <section>",
            "    <h2>Operational Impact</h2>",
            f"    <p>{_escape(analysis.operational_impact)}</p>",
            "  </section>",
            "  <section>",
            "    <h2>Cost Impact</h2>",
            f"    <p>{_escape(analysis.cost_impact)}</p>",
            "  </section>",
            "  <section>",
            "    <h2>Recommendations</h2>",
            recommendations,
            "  </section>",
            "  <footer>",
            "    <p>Generated by DriftMind.</p>",
            "  </footer>",
            "</body>",
            "</html>",
        )
    )


def _plain(value: str) -> str:
    return value.replace("\r\n", "\n").replace("\r", "\n")


def format_text_report(
    analysis: ExecutiveAnalysis,
    generated_at: datetime,
) -> str:
    """Render a readable plain-text alternative with matching content."""
    if not isinstance(analysis, ExecutiveAnalysis):
        raise ReportFormattingError("analysis must be an ExecutiveAnalysis")
    analysis.validate()
    timestamp = _format_timestamp(generated_at)
    if analysis.recommendations:
        recommendations = "\n".join(
            f"- {_plain(recommendation.text)}"
            for recommendation in analysis.recommendations
        )
    else:
        recommendations = "- No recommendations provided."

    return "\n".join(
        (
            REPORT_TITLE,
            f"Generated: {timestamp}",
            "",
            "Executive Summary",
            _plain(analysis.summary),
            "",
            "Security Impact",
            _plain(analysis.security_impact),
            "",
            "Operational Impact",
            _plain(analysis.operational_impact),
            "",
            "Cost Impact",
            _plain(analysis.cost_impact),
            "",
            "Recommendations",
            recommendations,
            "",
            "Footer",
            "Generated by DriftMind.",
        )
    )


def format_notification(
    analysis: ExecutiveAnalysis,
    generated_at: datetime,
) -> NotificationRequest:
    """Create the validated HTML/text request consumed by the SES adapter."""
    request = NotificationRequest(
        subject=REPORT_TITLE,
        text_body=format_text_report(analysis, generated_at),
        html_body=format_html_report(analysis, generated_at),
    )
    request.validate()
    return request
