"""Unit tests for the Phase 5 Notification and Reporting Engine."""

from __future__ import annotations

import importlib
import unittest
from datetime import datetime, timezone
from email import policy
from email.parser import BytesParser
from unittest.mock import Mock

_ai_models = importlib.import_module("lambda.ai.models")
_email = importlib.import_module("lambda.notification.email")
_formatter = importlib.import_module("lambda.notification.formatter")
_models = importlib.import_module("lambda.notification.models")
_service = importlib.import_module("lambda.notification.service")

ExecutiveAnalysis = _ai_models.ExecutiveAnalysis
Recommendation = _ai_models.Recommendation
SESEmailClient = _email.SESEmailClient
SESDeliveryError = _email.SESDeliveryError
NotificationResult = _models.NotificationResult
NotificationService = _service.NotificationService
format_html_report = _formatter.format_html_report
format_text_report = _formatter.format_text_report
format_notification = _formatter.format_notification

FIXED_TIME = datetime(2026, 7, 18, 12, 34, 56, tzinfo=timezone.utc)
SES_ENV = {
    "AWS_REGION": "us-east-1",
    "SES_SENDER": "sender@example.com",
    "SES_RECIPIENT": "recipient@example.com",
}


def make_analysis() -> ExecutiveAnalysis:
    return ExecutiveAnalysis(
        summary='<script>alert("summary")</script> & reviewed',
        security_impact="No security field changed.",
        operational_impact="Capacity increased.\nMonitor utilization.",
        cost_impact="No pricing data was provided.",
        recommendations=(
            Recommendation("Review <CHG-0001> & confirm capacity."),
            Recommendation("Monitor the deployment."),
        ),
    )


class ReportFormatterTests(unittest.TestCase):
    def test_html_formatting_is_deterministic_and_escaped(self) -> None:
        analysis = make_analysis()

        first = format_html_report(analysis, FIXED_TIME)
        second = format_html_report(analysis, FIXED_TIME)

        self.assertEqual(first, second)
        self.assertIn("DriftMind Infrastructure Intelligence Report", first)
        self.assertIn("2026-07-18T12:34:56Z", first)
        for section in (
            "Executive Summary",
            "Security Impact",
            "Operational Impact",
            "Cost Impact",
            "Recommendations",
        ):
            self.assertIn(f"<h2>{section}</h2>", first)
        self.assertIn("&lt;script&gt;alert(&quot;summary&quot;)&lt;/script&gt; &amp; reviewed", first)
        self.assertNotIn("<script>", first)
        self.assertIn("Review &lt;CHG-0001&gt; &amp; confirm capacity.", first)
        self.assertNotIn("<style", first)
        self.assertNotIn("<script", first)
        self.assertIn("<footer>", first)

    def test_plain_text_contains_matching_readable_content(self) -> None:
        report = format_text_report(make_analysis(), FIXED_TIME)

        self.assertIn("DriftMind Infrastructure Intelligence Report", report)
        self.assertIn("Generated: 2026-07-18T12:34:56Z", report)
        self.assertIn('<script>alert("summary")</script> & reviewed', report)
        self.assertIn("Capacity increased.\nMonitor utilization.", report)
        self.assertIn("- Review <CHG-0001> & confirm capacity.", report)
        self.assertIn("Footer\nGenerated by DriftMind.", report)


class SESEmailClientTests(unittest.TestCase):
    def test_ses_success_returns_typed_delivery_result(self) -> None:
        ses_client = Mock()
        ses_client.send_raw_email.return_value = {"MessageId": "message-123"}
        client = SESEmailClient(environ=SES_ENV, ses_client=ses_client)

        result = client.send(format_notification(make_analysis(), FIXED_TIME))

        self.assertEqual(
            result.to_dict(), {"message_id": "message-123", "status": "sent"}
        )
        ses_client.send_raw_email.assert_called_once()

    def test_ses_failure_is_redacted_and_has_no_provider_cause(self) -> None:
        ses_client = Mock()
        ses_client.send_raw_email.side_effect = RuntimeError(
            "provider failure containing secret material"
        )
        client = SESEmailClient(environ=SES_ENV, ses_client=ses_client)

        with self.assertRaisesRegex(
            SESDeliveryError, "SES notification delivery failed"
        ) as raised:
            client.send(format_notification(make_analysis(), FIXED_TIME))

        self.assertNotIn("secret material", str(raised.exception))
        self.assertIsNone(raised.exception.__cause__)

    def test_generated_message_is_multipart_alternative(self) -> None:
        ses_client = Mock()
        ses_client.send_raw_email.return_value = {"MessageId": "message-123"}
        client = SESEmailClient(environ=SES_ENV, ses_client=ses_client)
        request = format_notification(make_analysis(), FIXED_TIME)

        client.send(request)

        invocation = ses_client.send_raw_email.call_args.kwargs
        self.assertEqual(invocation["Source"], "sender@example.com")
        self.assertEqual(invocation["Destinations"], ["recipient@example.com"])
        message = BytesParser(policy=policy.default).parsebytes(
            invocation["RawMessage"]["Data"]
        )
        self.assertEqual(message.get_content_type(), "multipart/alternative")
        parts = list(message.iter_parts())
        self.assertEqual(
            [part.get_content_type() for part in parts],
            ["text/plain", "text/html"],
        )
        self.assertIn(request.text_body, parts[0].get_content())
        self.assertIn(request.html_body, parts[1].get_content())


class NotificationServiceTests(unittest.TestCase):
    def test_service_orchestrates_formatting_and_delivery(self) -> None:
        client = Mock()
        client.send.return_value = NotificationResult(message_id="message-123")
        service = NotificationService(client=client, clock=lambda: FIXED_TIME)

        result = service.notify(make_analysis())

        self.assertEqual(result.message_id, "message-123")
        client.send.assert_called_once()
        request = client.send.call_args.args[0]
        self.assertEqual(
            request.subject, "DriftMind Infrastructure Intelligence Report"
        )
        self.assertIn("2026-07-18T12:34:56Z", request.text_body)
        self.assertIn("2026-07-18T12:34:56Z", request.html_body)


if __name__ == "__main__":
    unittest.main()
